# Forces new Travis-CI Infrastructure
sudo: false

language: php

addons:
  chrome: stable
  apt:
    packages:
    - xvfb
    - fluxbox

env:
  global:
    - RUN_PHPCS="no"

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env: RUN_PHPCS="yes"
    - php: 7.0
      sudo: true
    - php: 7.1
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Until the next stable image update sometime after 2016-12-01
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
  allow_failures:
    - php: hhvm

before_script:
# Xvfb
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Fluxbox
- sudo apt-get install fluxbox -y --force-yes
- fluxbox &
- sleep 3 # give fluxbox some time to start
# Composer
- composer install

script:
# Build
- mv jorobo.dist.ini jorobo.ini
- vendor/bin/robo build
# System tests (Codeception)
- mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
- vendor/bin/robo run:tests --use-htaccess
# Run phpcs on PHP 5.6 against weblinks source
- if [[ $RUN_PHPCS == "yes" ]]; then vendor/bin/phpcs --report=full --extensions=php -p --standard=tests/joomla/build/phpcs/Joomla ./src; fi
